:sparkles: bak improvements

diff --git a/dotfiles/bin/bak b/dotfiles/bin/bak
--- a/dotfiles/bin/bak
+++ b/dotfiles/bin/bak
@@ -1,77 +1,109 @@
 #!/usr/bin/env bash
 
-hflag=no # help
-nflag=no # nodelete - do not delete files
-rflag=no # recursion
-lflag=no # list files (performs delete anyway)
-aflag=no # all - flags r + p
-dflag=no # specify directory
-pflag=no # pyc - consider .pyc file
+help_flag=no      # help
+dryrun_flag=no    # nodelete - do not delete files
+recursive_flag=no # recursion
+listfiles_flag=no # list files (performs delete anyway)
+all_flag=no       # all - flags r + p
+directory_flag=no # specify directory
+python_flag=no    # pyc - consider .pyc file
+node_flag=no      # node_modules
+ruby_flag=no      # gems
+autoyes_flag=no   # do not ask for confirmation
 directory=""
-startdir=`pwd`
-TMP=bak`date +%s`
+startdir=$(pwd)
+TMP=bak$(date +%s)
+
+# http://en.wikipedia.org/wiki/ANSI_escape_code#CSI_Codes
+esc_red='\033[91m'
+esc_green='\033[92m'
+esc_cyan='\033[96m'
+esc_yellow='\033[93m'
+esc_reset='\033[0m'
 
 ####################################################################################
 # GETOPT
 
-set -- $(getopt hnrplasd: "$@")
-while [ $# -gt 0 ]
-do
-    case "$1" in
-    (-h) hflag=yes;;
-    (-n) nflag=yes;;
-    (-r) rflag=yes;;
-    (-p) pflag=yes;;
-    (-l) lflag=yes;;
-    (-a) pflag=yes; rflag=yes;;
-    (-d) dflag=yes; directory="$directory $2"; shift;;
-    (--) shift; break;;
-    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
-    (*)  break;;
-    esac
+set -- $(getopt hynrpoblasd: "$@")
+while [ $# -gt 0 ]; do
+  case "$1" in
+  -h) help_flag=yes ;;
+  -y) autoyes_flag=yes ;;
+  -n) dryrun_flag=yes ;;
+  -r) recursive_flag=yes ;;
+  -p) python_flag=yes ;;
+  -o) node_flag=yes ;;
+  -b) ruby_flag=yes ;;
+  -l) listfiles_flag=yes ;;
+  -a)
+    python_flag=yes
+    recursive_flag=yes
+    listfiles_flag=yes
+    ;;
+  -d)
+    directory_flag=yes
+    directory="$directory $2"
     shift
+    ;;
+  --)
+    shift
+    break
+    ;;
+  -*)
+    echo "$0: error - unrecognized option $1" 1>&2
+    exit 1
+    ;;
+  *) break ;;
+  esac
+  shift
 done
 
 ####################################################################################
 # HELP FLAG
 # print help and exit
 
-if [ $hflag = yes ]; then
-	echo "Usage: bak [-rpslna] [-d DIRECTORY]"
-    echo "  Deletes backup files ( *~ )"
-    echo "  If no DIRECTORY deletes in current directory"
-    echo
-    echo "Options:"
-    echo "   -r     Recursive"
-    echo "   -p     Delete also .pyc"
-    echo "   -l     Print files list"
-    echo "   -n     Dry run (no delete)"
-    echo "   -a     Alias for -prs"
-	echo
-    exit 0
+if [ $help_flag = yes ]; then
+  echo -e "${esc_cyan}Usage:${esc_reset}"
+  echo -e "  bak [${esc_yellow}-rpslna${esc_reset}] [${esc_yellow}-d DIRECTORY${esc_reset}]"
+  echo
+  echo -e "${esc_cyan}Infos:${esc_reset}"
+  echo -e "  Utility to delete backup and temporary files such as ${esc_red}*~${esc_reset} or ${esc_red}.DS_Store${esc_reset}"
+  echo -e "  Default ${esc_yellow}DIRECTORY${esc_reset} is ${esc_yellow}.${esc_reset}"
+  echo
+  echo -e "${esc_cyan}Options:${esc_reset}"
+  echo -e "   ${esc_yellow}-a${esc_reset}     Alias for ${esc_yellow}-rlp${esc_reset}"
+  echo -e "   ${esc_yellow}-r${esc_reset}     Recursive"
+  echo -e "   ${esc_yellow}-l${esc_reset}     Print files list"
+  echo -e "   ${esc_yellow}-p${esc_reset}     Delete also Python ${esc_red}*pyc${esc_reset}"
+  echo -e "   ${esc_yellow}-o${esc_reset}     Delete also Node ${esc_red}node_modules${esc_reset}"
+  echo -e "   ${esc_yellow}-b${esc_reset}     Delete also Ruby ${esc_red}vendor/bundle${esc_reset}"
+  echo -e "   ${esc_yellow}-y${esc_reset}     Do not ask for confirmation to delete"
+  echo -e "   ${esc_yellow}-n${esc_reset}     Dry run (no delete)"
+  echo
+  exit 0
 fi
 
 ####################################################################################
 # PREPARE
 
 # Directory
-if [ $dflag = yes ]; then
-    # check if given directory is a directory
-    if [ ! -d $directory ] ; then
-        echo "'$directory' is not a directory"
-        exit 1
-    fi
+if [ $directory_flag = yes ]; then
+  # check if given directory is a directory
+  if [ ! -d $directory ]; then
+    echo "'$directory' is not a directory"
+    exit 1
+  fi
 else
-    # no directory given, assumes .
-    directory=`pwd`
+  # no directory given, assumes .
+  directory=$(pwd)
 fi
 
 # Recursion
 depth='-maxdepth 1'
 andits=''
-if [ $rflag = yes ]; then
-    depth='' #recursive
-    andits=' and its subdirectories'
+if [ $recursive_flag = yes ]; then
+  depth='' #recursive
+  andits=' and its subdirectories'
 fi
 
 ####################################################################################
@@ -79,39 +111,69 @@ fi
 
 cd $directory
 
-# http://en.wikipedia.org/wiki/ANSI_escape_code#CSI_Codes
-esc_red='\033[91m'
-esc_green='\033[92m'
-esc_reset='\033[0m'
-
 #list files in TMP file
-find . -name "*~" $depth -exec echo "\"{}\"" \; > /tmp/$TMP 2> /dev/null
-find . -name ".DS_Store" $depth -exec echo "\"{}\"" \; >> /tmp/$TMP 2> /dev/null
-find . -name "*.dotdropbak" $depth -exec echo "\"{}\"" \; >> /tmp/$TMP 2> /dev/null
+echo -e "Looking for ${esc_yellow}*~${esc_reset}"
+find . -name "*~" $depth -exec echo "\"{}\"" \; >/tmp/$TMP 2>/dev/null
+echo -e "Looking for ${esc_yellow}.DS_Store${esc_reset}"
+find . -name ".DS_Store" $depth -exec echo "\"{}\"" \; >>/tmp/$TMP 2>/dev/null
+echo -e "Looking for ${esc_yellow}*.dotdropbak${esc_reset}"
+find . -name "*.dotdropbak" $depth -exec echo "\"{}\"" \; >>/tmp/$TMP 2>/dev/null
 
-if [ $pflag = yes ]; then
-    find . -name "*pyc" $depth -exec echo "\"{}\"" \; >> /tmp/$TMP 2> /dev/null
+if [ $python_flag = yes ]; then
+  echo -e "Looking for ${esc_yellow}*pyc${esc_reset}"
+  find . -name "*pyc" $depth -exec echo "\"{}\"" \; >>/tmp/$TMP 2>/dev/null
 fi
 
+if [ $ruby_flag = yes ]; then
+  echo -e "Looking for ${esc_yellow}vendor/bundle${esc_reset}"
+  # find all `vendor/bundle`
+  find . -type d -name "vendor" -o -type d -name "bundle" -prune $depth -exec echo "\"{}\"" \; >>/tmp/$TMP 2>/dev/null
+fi
 
-FILES=`wc -l /tmp/$TMP | cut -d/ -f1 | sed 's/[ ]//g' `
-if [ ${FILES} -ge 1 ] ; then
+if [ $node_flag = yes ]; then
+  echo -e "Looking for ${esc_yellow}node_modules${esc_reset}"
+  # find all `node_modules` (except if inside a `gem` folder)
+  find . -type d -name "gems" -prune -o -type d -name "node_modules" -prune $depth -exec echo "\"{}\"" \; >>/tmp/$TMP 2>/dev/null
+fi
 
-    if [ $lflag = yes ]; then
-        # list files
-        cat -n /tmp/$TMP | sed 's/"//g'
-        echo
-    fi
+echo
 
-    if [ $nflag = no ]; then
-        cat /tmp/$TMP | xargs rm -f #delete
-        echo -e "$FILES bak files ${esc_red}deleted${esc_reset} in ${esc_green}$directory${esc_reset}$andits"
+FILES=$(wc -l /tmp/$TMP | cut -d/ -f1 | sed 's/[ ]//g')
+if [ ${FILES} -ge 1 ]; then
+
+  if [ $listfiles_flag = yes ]; then
+    # list files
+    cat -n /tmp/$TMP | sed 's/"//g'
+    echo
+  fi
+
+  if [ $dryrun_flag = no ]; then
+
+    confirm=no
+    if [ $autoyes_flag = yes ]; then
+      confirm=yes
     else
-        echo -e "$FILES bak files listed in ${esc_green}$directory${esc_reset}$andits"
+      read -n 1 -p "Delete files and directories? (y/N)? " answer
+      case ${answer:0:1} in
+      y | Y)
+        confirm=yes
+        ;;
+      esac
+      echo
     fi
+
+    if [ $confirm = yes ]; then
+      cat /tmp/$TMP | xargs rm -rf #delete
+      echo -e "$FILES bak files ${esc_red}deleted${esc_reset} in ${esc_green}$directory${esc_reset}$andits"
+    else
+      echo -e "Aborted"
+    fi
+  else
+    echo -e "$FILES bak files listed in ${esc_green}$directory${esc_reset}$andits"
+  fi
 
 else
-    echo -e "No bak files listed in ${esc_green}$directory${esc_reset}$andits"
+  echo -e "No bak files listed in ${esc_green}$directory${esc_reset}$andits"
 fi
 
 #remove TMP file
