update zbm

diff --git a/dotfiles/bin/update-zbm b/dotfiles/bin/update-zbm
--- a/dotfiles/bin/update-zbm
+++ b/dotfiles/bin/update-zbm
@@ -1,94 +1,124 @@
-#! /usr/bin/env zsh
+#! /usr/bin/env bash
 
 # Root check:
-if [[ ! ${UID} == 0 ]]; then
-  print "You need root privileges to run this."
-  exit -1
+if [[ ! 0 == ${UID} ]]; then
+  echo "You need root privileges to run this."
+  exit 1
 fi
 
-# Dependencies check:
-for D in curl efibootmgr sed grep umount mount; do
+# Dependencies check (better safe than sorry):
+for D in curl efibootmgr grep mount sed umount; do
   if [[ ! $(command -v ${D}) ]]; then
-    print "Command not found: ${D}"
-    exit -1
+    echo "Command not found: ${D}"
+    unset D
+    exit 1
   fi
 done
 
-# Utility cleanup function.
+# Utility cleanup function, takes as parameter the exit value:
 function cleanup() {
   umount "${EFI}" &>/dev/null
-  rmdir "${EFI}"
-  rm "/tmp/zfsbootmenu.EFI" &>/dev/null
-  unset DEPS d EFI EBM EFI_DEVICE ZBM_PATH DATA LATEST URL INSTALLED
+  rmdir "${EFI}" &>/dev/null
+  rm "${TMP_DWN}" &>/dev/null
+  unset D EFI EBM EFI_DEVICE ZBM_PATH DATA LATEST URL INSTALLED TMP_DWN
+  exit $1
 }
-
-# Temporary EFI mountpoint:
-EFI="/root/efi_$(date "+%Y%m%d%H%M%S")"
-mkdir "${EFI}"
 
 # Get zfsbootmenu's entry:
 EBM=$(efibootmgr --verbose | grep -i zfsbootmenu.EFI | sed -E 's,\\,\\\\,g')
+if [[ "" == ${EBM} ]]; then
+  echo "No existing ZBM entry found via efibootmgr."
+  cleanup 2
+fi
 
-# Get EFI's partuuid:
-EFI_DEVICE="/dev/disk/by-partuuid/$(print ${EBM} | sed -E 's/(.*GPT,|,.*)//g')"
+# Temporary EFI mountpoint:
+EFI="/root/efi_$(date "+%Y%m%d%H%M%S")"
+mkdir -p "${EFI}"
+
+# Fidn the EFI device via partuuid:
+EFI_DEVICE="/dev/disk/by-partuuid/$(sed -E 's/(.*GPT,|,.*)//g' <<<${EBM})"
 
 # Get ZBM's path inside the EFI partition:
-ZBM_PATH="${EFI}$(print ${EBM} | sed -E 's,(\\zfsbootmenu\.EFI\).*|.*\(),,g' | sed -E 's,\\,/,g')"
+ZBM_PATH="${EFI}/$(
+  sed -E 's,(\\zfsbootmenu\.EFI\).*|.*\(\\\\),,g' <<<${EBM} |
+    sed -E 's,\\,/,g'
+)/zfsbootmenu.EFI"
 
-# Mount EFI:
+# Temporary ZBM download path:
+TMP_DWN="/tmp/zfsbootmenu.EFI"
+
+# Mount EFI partition:
 umount "${EFI_DEVICE}" &>/dev/null
-mount "${EFI_DEVICE}" "${EFI}" &>/dev/null
+mount \
+  -o rw \
+  -o relatime \
+  -o fmask=0177 \
+  -o dmask=0077 \
+  -o codepage=437 \
+  -o iocharset=iso8859-1 \
+  -o shortname=mixed \
+  -o utf8 \
+  "${EFI_DEVICE}" "${EFI}" &>/dev/null
 if [[ ! 0 == $? ]]; then
-  print "Failed to mount ${EFI_DEVICE}."
-  cleanup
-  exit -2
+  echo "Failed to mount ${EFI_DEVICE}."
+  cleanup 3
 fi
 
-# Obtain version data from git:
-DATA=$(curl --silent "https://api.github.com/repos/zbm-dev/zfsbootmenu/releases/latest")
-
-# If curl fails there's no point in moving forward:
+# Ensure this path exists in case EFI partition is empty but efibootmngr
+# reports an entry
+mkdir -p "$(dirname ${ZBM_PATH})"
 if [[ ! 0 == $? ]]; then
-  print "Failed to fetch data from git."
-  cleanup
-  exit -3
+  echo "Failed to create ZBM folder in EFI partition."
+  cleanup 4
 fi
 
-# Parse git data:
-LATEST=$(print ${DATA} | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
-URL=$(print ${DATA} | grep browser_download_url | grep -e ".*release-.*EFI.*" | sed -E 's/(^.* "|".*$)//g')
-
-# Find out the installed version if available:
-if [[ -f "${EFI}/EFI/zbm/version" ]]; then
-  INSTALLED=$(cat "${ZBM_PATH}/version")
+# Fetch info about the latest release from git:
+DATA=$(
+  curl --silent \
+    "https://api.github.com/repos/zbm-dev/zfsbootmenu/releases/latest"
+)
+if [[ ! 0 == $? ]]; then
+  echo "Failed to fetch data from git."
+  cleanup 5
 fi
 
-# Print some info:
-print "Latest version: ${LATEST}"
-print "Installed version: ${INSTALLED}"
+# Parse latest release data:
+LATEST=$(grep '"tag_name":' <<<${DATA} | sed -E 's/.*"([^"]+)".*/\1/')
+URL=$(
+  grep browser_download_url <<<${DATA} |
+    grep -e ".*release-.*EFI.*" |
+    sed -E 's/(^.* "|".*$)//g'
+)
 
-# Only update if necessary:
+# Installed version (if info is available):
+INSTALLED=$(cat "${ZBM_PATH}.version" 2>/dev/null)
+
+# Print out some info:
+echo "Latest version: ${LATEST}"
+echo "Installed version: ${INSTALLED}"
+
+# Update ZBM if necessary:
 if [[ ! ${INSTALLED} == ${LATEST} ]]; then
-  # Download ZBM in a temporary folder:
-  rm "/tmp/zfsbootmenu.EFI" &>/dev/null
-  curl -L "${URL}" -o "/tmp/zfsbootmenu.EFI"
+  echo -e "\nDownloading latest version via curl:"
 
-  # If the download fails just stop:
+  # Download ZBM in a temporary folder:
+  rm "${TMP_DWN}" &>/dev/null
+  curl -L "${URL}" -o "${TMP_DWN}"
   if [[ ! 0 == $? ]]; then
-    print "Failed to download latest ZBM."
-    cleanup
-    exit -4
+    echo "Failed to download latest ZBM."
+    cleanup 6
   fi
 
-  # Backup the previous version:
-  rm "${ZBM_PATH}/zfsbootmenu.EFI.old" &>/dev/null
-  mv "${ZBM_PATH}/zfsbootmenu.EFI" "${ZBM_PATH}/zfsbootmenu.EFI.old"
-  print "${INSTALLED}" >|"${ZBM_PATH}/version.old"
+  # Backup the previous version if needed:
+  if [[ -e "${ZBM_PATH}" ]]; then
+    mv -f "${ZBM_PATH}" "${ZBM_PATH}.old"
+    echo "${INSTALLED}" >"${ZBM_PATH}.old.version"
+  fi
 
   # Move in the new version:
-  mv "/tmp/zfsbootmenu.EFI" "${ZBM_PATH}/zfsbootmenu.EFI"
-  print "${LATEST}" >|"${ZBM_PATH}/version"
+  mv "${TMP_DWN}" "${ZBM_PATH}"
+  echo "${LATEST}" >"${ZBM_PATH}.version"
 fi
 
 # Final touches:
-cleanup
+cleanup 0
